# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Калькулятор")
        Dialog.resize(400, 700)
        self.a = ''
        self.b = ''
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 130, 71, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 130, 71, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 220, 71, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 130, 71, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 220, 71, 61))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(280, 220, 71, 61))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 310, 71, 61))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(160, 310, 71, 61))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(280, 310, 71, 61))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(40, 580, 71, 61))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(160, 400, 71, 61))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(40, 400, 71, 141))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(160, 490, 71, 61))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(160, 580, 191, 61))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(280, 400, 71, 141))
        self.pushButton_16.setObjectName("pushButton_16")
        self.textEdit.setGeometry(QtCore.QRect(40, 30, 321, 71))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_2.setText(_translate("Dialog", "1"))
        self.pushButton_2.clicked.connect(self.btn1)
        self.pushButton_3.setText(_translate("Dialog", "2"))
        self.pushButton_3.clicked.connect(self.btn2)
        self.pushButton_4.setText(_translate("Dialog", "4"))
        self.pushButton_4.clicked.connect(self.btn4)
        self.pushButton_5.setText(_translate("Dialog", "3"))
        self.pushButton_5.clicked.connect(self.btn3)
        self.pushButton_6.setText(_translate("Dialog", "5"))
        self.pushButton_6.clicked.connect(self.btn5)
        self.pushButton_7.setText(_translate("Dialog", "6"))
        self.pushButton_7.clicked.connect(self.btn6)
        self.pushButton_8.setText(_translate("Dialog", "7"))
        self.pushButton_8.clicked.connect(self.btn7)
        self.pushButton_9.setText(_translate("Dialog", "8"))
        self.pushButton_9.clicked.connect(self.btn8)
        self.pushButton_10.setText(_translate("Dialog", "9"))
        self.pushButton_10.clicked.connect(self.btn9)
        self.pushButton_11.setText(_translate("Dialog", "*"))
        # self.pushButton_11.clicked.connect(self.btnU)
        self.pushButton_12.setText(_translate("Dialog", "0"))
        self.pushButton_12.clicked.connect(self.btn0)
        self.pushButton_13.setText(_translate("Dialog", "-"))
        # self.pushButton_13.clicked.connect(self.btnM)
        self.pushButton_14.setText(_translate("Dialog", "/"))
        # self.pushButton_14.clicked.connect(self.btnD)
        self.pushButton_15.setText(_translate("Dialog", "="))
        # self.pushButton_15.clicked.connect(self.btnE)
        self.pushButton_16.setText(_translate("Dialog", "+"))
        # self.pushButton_16.clicked.connect(self.Plus)



    def btn1(self):
        self.a = str(self.a) + '1'
        self.textEdit.setText(self.a)
    def btn2(self):
        self.a = str(self.a) + '2'
        self.textEdit.setText(self.a)
    def btn3(self):
        self.a = str(self.a) + '3'
        self.textEdit.setText(self.a)
    def btn4(self):
        self.a = str(self.a) + '4'
        self.textEdit.setText(self.a)
    def btn5(self):
        self.a = str(self.a) + '5'
        self.textEdit.setText(self.a)
    def btn6(self):
        self.a = str(self.a) + '6'
        self.textEdit.setText(self.a)
    def btn7(self):
        self.a = str(self.a) + '7'
        self.textEdit.setText(self.a)
    def btn8(self):
        self.a = str(self.a) + '8'
        self.textEdit.setText(self.a)
    def btn9(self):
        self.a = str(self.a) + '9'
        self.textEdit.setText(self.a)
    def btn0(self):
        self.a = str(self.a) + '0'
        self.textEdit.setText(self.a)
    # def btnM(self):
    #     self.a = str(self.a) + '2'
    # def btnD(self):
    #     self.a = str(self.a) + '2'
    # def btnU(self):
    #     self.a = str(self.a) + '2'
    # def btnE(self):
    #     self.a = str(self.a) + '2'
    # def btnPLUS(self):
    #    self.a = str(self.a) + '2'

    def flag(self):
        self.flag()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
